
- id: '1755538082640'
  alias: 'Living Room activate Air Condition '
  description: ''
  triggers:
  - type: temperature
    device_id: 59d0663b361b0e3d40fe2981b7e502b0
    entity_id: 1941c01a274fdb4071ea6f9e9d7fa840
    domain: sensor
    trigger: device
    above: 29
  conditions:
  - condition: time
    after: '10:00:00'
    before: '15:00:00'
  actions:
  - device_id: f8c49e66b93b97741e9863dd46369eb5
    domain: climate
    entity_id: cad480b0c1bbf243e76e004433182290
    type: set_hvac_mode
    hvac_mode: cool
  mode: single









- id: '1763831152810'
  alias: 'Keep Water Temperature at 25C '
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.shellyplusuni_78421c52e014_temperature
    below: 25
  conditions: []
  actions:
  - type: turn_on
    device_id: c701e7934ca9f549e8d10469ba7f7470
    entity_id: 20de7c42b6ee9db248c7d1feaae2ec7e
    domain: switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: c701e7934ca9f549e8d10469ba7f7470
    entity_id: 20de7c42b6ee9db248c7d1feaae2ec7e
    domain: switch
  mode: single

