views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/scenes.yaml
  - !include lovelace/views/energyview.yaml
  - !include lovelace/views/internet.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/batteries.yaml
  - !include lovelace/views/air_condition.yaml
  - !include lovelace/views/system.yaml
  - !include lovelace/views/family.yaml