esphome:
  name: water-tank
  friendly_name: Water Tank
  platformio_options:
    platform: file:///root/.platformio/platforms/espressif32
    framework: espidf
    
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/j5iDHDDST4O+3NTPC2huaAil0SqohvAb7ujAwy73i0="

ota:
  - platform: esphome
    password: "528d49162b2b476201b1be8b1d915a0f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Tank Fallback Hotspot"
    password: "YbRUIyg7EbkZ"

captive_portal:
    