automation:

  - id: grid_on_then_turn_on_fridge
    alias: Grid On then Turn on Fridge
    trigger:
      - platform: state
        entity_id: binary_sensor.power_grid_available
        to: "on"
        for:
          minutes: 1
    condition:
      - condition: time
        after: "19:36:00"
        before: "07:36:00"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.sonoff_1002182e4e
    mode: single

  - id: grid_off_then_turn_off_fridge
    alias: Grid Off then Turn off Fridge
    trigger:
      - platform: state
        entity_id: binary_sensor.power_grid_available
        to: "off"
        for:
          minutes: 1
    condition:
      - condition: time
        after: "19:36:00"
        before: "07:36:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.sonoff_1002182e4e
    mode: single

  - id: turn_on_fridge_morning
    alias: Turn on Fridge Morning
    trigger:
      - platform: time
        at: "07:35:00"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.sonoff_1002182e4e
    mode: single

  - id: turn_off_fridge_evening
    alias: Turn off Fridge Evening
    trigger:
      - platform: time
        at: "19:35:00"
    condition:
      - condition: state
        entity_id: binary_sensor.power_grid_available
        state: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.sonoff_1002182e4e
    mode: single

  - id: fridge_on_notification
    alias: Fridge on Notification
    trigger:
      - platform: state
        entity_id: switch.sonoff_1002182e4e
        to: "on"
    action:
      - service: telegram_bot.send_message
        data:
          message: "🧊 البراد يعمل الآن"
    mode: single

  - id: fridge_off_notification
    alias: Fridge off Notification
    trigger:
      - platform: state
        entity_id: switch.sonoff_1002182e4e
        to: "off"
    action:
      - service: telegram_bot.send_message
        data:
          message: "🚫 البراد متوقف عن العمل"
    mode: single

  - id: fridge_temperature_over_6_notification
    alias: Fridge Temperature is over 6 degrees Notification
    trigger:
      - platform: numeric_state
        entity_id: sensor.shellyplusuni_a0dd6c295c74_fridge_temperature_sensor_temperature
        above: 6
    action:
      - service: telegram_bot.send_message
        data:
          message: "🥶 حرارة البراد تجاوزت 6 درجات"

      - service: switch.turn_on
        target:
          entity_id: switch.sonoff_1002182e4e

      - delay:
          minutes: 15

      - if:
          - condition: time
            after: "19:35:00"
            before: "07:35:00"
          - condition: state
            entity_id: binary_sensor.power_grid_available
            state: "off"
        then:
          - service: switch.turn_off
            target:
              entity_id: switch.sonoff_1002182e4e
    mode: single