
automation:
  - id: '1757222373993'
    alias: 'Power Grid On Notification'
    description: ''
    triggers:
    - type: power
      device_id: d2083923ab583c1c87377258f7e41951
      entity_id: 4bb688679aaaa5d6af15421bdba33af0
      domain: sensor
      trigger: device
      above: 10
      for:
        seconds: 5
    conditions: []
    actions:
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: 'Power Grid On '
    mode: single

  - id: '1757222420874'
    alias: 'Power Grid Off Notification '
    description: ''
    triggers:
    - type: power
      device_id: d2083923ab583c1c87377258f7e41951
      entity_id: 4bb688679aaaa5d6af15421bdba33af0
      domain: sensor
      trigger: device
      below: 1
      for:
        seconds: 5
    conditions: []
    actions:
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: Power Grid Off
    mode: single

  - id: '1757222625298'
    alias: 'Power Grid > 2000 W'
    description: ''
    triggers:
    - type: power
      device_id: d2083923ab583c1c87377258f7e41951
      entity_id: 4bb688679aaaa5d6af15421bdba33af0
      domain: sensor
      trigger: device
      above: 2000
      for:
        hours: 0
        minutes: 0
        seconds: 5
    conditions: []
    actions:
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: Power Grid consumption is over 2000W
    mode: single

  - id: '1772452747191'
    alias: Power Grid Not Stable
    description: ''
    triggers:
    - type: power
      device_id: d2083923ab583c1c87377258f7e41951
      entity_id: 4bb688679aaaa5d6af15421bdba33af0
      domain: sensor
      trigger: device
      above: 230
      for:
        hours: 0
        minutes: 0
        seconds: 1
    - type: power
      device_id: d2083923ab583c1c87377258f7e41951
      entity_id: 4bb688679aaaa5d6af15421bdba33af0
      domain: sensor
      trigger: device
      below: 180
      for:
        hours: 0
        minutes: 0
        seconds: 1
    conditions: []
    actions:
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: Power Grid is not stable
    mode: single
    max: 10

  - id: '1772452794689'
    alias: Power Grid Off 4 Hours Notification
    description: ''
    triggers:
    - type: power
      device_id: d2083923ab583c1c87377258f7e41951
      entity_id: 4bb688679aaaa5d6af15421bdba33af0
      domain: sensor
      trigger: device
      below: 1
      for:
        hours: 4
        minutes: 0
        seconds: 0
    conditions: []
    actions:
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: 'Power Grid has been off for more than 4 hours!'
    mode: single
