
automation:
  - id: '1757222373993'
    alias: 'Power Grid On Notification'
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.sonoff_1002328b17_power
      above: 1
      for:
        minutes: 1
    condition: []
    action:
    - service: telegram_bot.send_message
      data:
        message: '✅ الكهرباء متوفرة الآن'
    mode: single

  - id: '1757222420874'
    alias: 'Power Grid Off Notification'
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.sonoff_1002328b17_power
      below: 1
      for:
        minutes: 1
    condition: []
    action:
    - service: telegram_bot.send_message
      data:
        message: '❌ الكهرباء غير متوفرة الآن'
    mode: single

  - id: '1757222625298'
    alias: 'Power Grid > 2000 W'
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.sonoff_1002328b17_power
      above: 2000
      for:
        seconds: 5
    condition: []
    action:
    - service: telegram_bot.send_message
      data:
        message: '⚠️ استهلاك الكهرباء يتجاوز 2000 واط'
    mode: single

  - id: '1772452747191'
    alias: Power Grid Not Stable
    description: 'Triggers when voltage is over 230V or under 180V'
    trigger:
      - platform: numeric_state
        entity_id: sensor.sonoff_1002328b17_voltage
        above: 230
        for:
          seconds: 5
      - platform: numeric_state
        entity_id: sensor.sonoff_1002328b17_voltage
        below: 180
        for:
          seconds: 5
    condition: []
    action:
    - service: telegram_bot.send_message
      data:
        message: '⚡️ تنبيه: الجهد الكهربائي غير مستقر! الجهد الحالي: {{ trigger.to_state.state }} فولت'
    mode: single

  - id: '1772452794689'
    alias: Power Grid Off 4 Hours Notification
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.sonoff_1002328b17_power
      below: 1
      for:
        hours: 4
    condition: []
    action:
    - service: telegram_bot.send_message
      data:
        message: '⏳ الكهرباء مقطوعة لأكثر من 4 ساعات!'
    mode: single
