template:
  - binary_sensor:
      - name: "Power Grid Available"
        unique_id: power_grid_available
        device_class: connectivity
        state: >
          {{ states('sensor.sonoff_1002328b17_power') not in ['unknown', 'unavailable', 'none', ''] }}

automation:
  - id: power_grid_on_notification
    alias: Power Grid On Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.power_grid_available
        to: "on"
        for:
          seconds: 10
    action:
      - service: telegram_bot.send_message
        data:
          message: "✅ الكهرباء متوفرة الآن"
    mode: single

  - id: power_grid_off_notification
    alias: Power Grid Off Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.power_grid_available
        to: "off"
        for:
          seconds: 10
    action:
      - service: telegram_bot.send_message
        data:
          message: "❌ الكهرباء غير متوفرة الآن"
    mode: single

  - id: '1772452747191'
    alias: Power Grid Not Stable
    description: 'Triggers when voltage is over 235V or under 180V'
    trigger:
      - platform: numeric_state
        entity_id: sensor.sonoff_1002328b17_voltage
        above: 235
        for:
          seconds: 5
      - platform: numeric_state
        entity_id: sensor.sonoff_1002328b17_voltage
        below: 180
        for:
          seconds: 5
    condition:
      - condition: state
        entity_id: binary_sensor.power_grid_available
        state: "on"
    action:
      - service: telegram_bot.send_message
        data:
          message: >
            ⚡️ تنبيه: الجهد الكهربائي غير مستقر!
            الجهد الحالي: {{ trigger.to_state.state }} فولت
    mode: single

  - id: power_grid_off_4_hours_notification
    alias: Power Grid Off 4 Hours Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.power_grid_available
        to: "off"
        for:
          hours: 4
    action:
      - service: telegram_bot.send_message
        data:
          message: "⏳ الكهرباء مقطوعة لأكثر من 4 ساعات!"
    mode: single