sensor:
  - platform: filter
    name: "Smoothed Water Tank Level"
    entity_id: sensor.shellyplusuni_78421c52e014_water_tank_sensor_voltmeter_value
    filters:
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 1

template:
  - sensor:
      - name: "Water Tank Level"
        unique_id: water_tank_level
        unit_of_measurement: "%"
        device_class: humidity
        state: >
          {% set v = states('sensor.shellyplusuni_78421c52e014_water_tank_sensor_voltmeter_value') | float(0) %}
          {% set percent = ((13.0 - v) / (13.0 - 12.21)) * 100 %}
          {{ [0, [percent | round(1), 100] | min] | max }}

automation:
  - id: '1744608000000'
    alias: 'تشغيل المضخة تلقائياً - خزان الماء أقل من 30%'
    description: 'تشغيل مضخة الماء تلقائياً عندما يصل مستوى الخزان إلى أقل من 30%'
    triggers:
    - trigger: numeric_state
      entity_id: sensor.water_tank_level
      below: 30
      for:
        minutes: 2
    conditions:
    - condition: state
      entity_id: switch.water_pump
      state: 'off'
    actions:
    - type: turn_on
      device_id: b1e1c93b5dc7eed8cf12cc274906d715
      entity_id: abe3d76f89feb5b6f5ae4d72bf1b919f
      domain: switch
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: >-
          ⚠️ مستوى خزان الماء أقل من 30% ({{ states('sensor.water_tank_level') }}%)
          تم تشغيل المضخة تلقائياً
    mode: single

