automation:
  - id: '1756848396086'
    alias: 'Window Shades Morning Open '
    description: ''
    triggers:
    - trigger: sun
      event: sunrise
      offset: "+01:00:00"
    conditions: []
    actions:
    - device_id: 6d402889ee8232a30b0983d0f31fbd9a
      domain: cover
      entity_id: 33dec1646b664ec817bae3194e549d56
      type: set_position
      position: 85
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: فتح الأباجور صباحاً
    mode: single

  - id: '1756848641209'
    alias: Window Shades Evening Closed
    description: ''
    triggers:
    - trigger: sun
      event: sunset
      offset: "-00:30:00"
    conditions: []
    actions:
    - device_id: 6d402889ee8232a30b0983d0f31fbd9a
      domain: cover
      entity_id: 33dec1646b664ec817bae3194e549d56
      type: set_position
      position: 0
    - action: telegram_bot.send_message
      metadata: {}
      data:
        message: إغلاق الأباجور مساءً
    mode: single
